### ISSUE TITLE
question on add function

### ISSUE THREAD

**Issue by mammenj** [coderconvoy/workers#3]
Hi, I have a question regarding the add function, I have modified as below:
for _, myfile := range files {
		//for i := 0; i < numoffiles; i++ {
		var l sync.Mutex
		wg.Add(func() {
			time.Sleep(time.Second / 10)
			l.Lock()
			log.Println("In main::: adding to function file::", myfile)
			l.Unlock()

		})
	}

but the file processed is always the last one, worker.go is same but with some logs.
2017/07/12 18:13:22 :::In NewWG::: Worker loop #  >>  1
2017/07/12 18:13:22 In NewWG::: ..Done.... new WG..
2017/07/12 18:13:22 In main:::number of files is  2
2017/07/12 18:13:22 In main::: ..Files*** : students1.csv
2017/07/12 18:13:22 In main::: ..Files*** : students2.csv
2017/07/12 18:13:22 :::In NewWG::: Addfunction()...
2017/07/12 18:13:22 :::In NewWG::: Addfunction()...
2017/07/12 18:13:22 :::In NewWG::: Waiting....
2017/07/12 18:13:22 ::: 2 - In NewWG::: Just before calling function
2017/07/12 18:13:22 ::: 2 - In NewWG::: Just before calling function
2017/07/12 18:13:22 In main::: adding to function file:: students2.csv
2017/07/12 18:13:22 In main::: adding to function file:: students2.csv

**Comment by chonlatee** [comment]
Can you post the full source code please.

I thing because you filename in func(){}  it's always get the last value

it's about value scope

**Comment by chonlatee** [comment]
if you try to use 
```go

files := [2]string{"file1", "file2"}

for _, file := range files {
   fmt.Println("file", file)
   func () {
    fmt.Println("file", file) 
  }
}
```

it will print 
```
  file file1
  file file2
  file file2
  file file2
```

**Comment by mammenj** [comment]
Thanks, yes by creating local variable it worked. my mistake as new to go.
