### ISSUE TITLE
race condition

### ISSUE THREAD

**Issue by allyraza** [coderconvoy/workers#4]
you asked me I need to show you where the problem is if you look at the code you might not see it because its very subtle you have a loop forking new routines the execution of these routines is not started until that loop is done right below that loop you have another loop in a routine iterating over the channel and pulling the values out you could have race between the 2 here is more idiomatic way do the same using std lib

```go
package main 

import (
    "fmt"
    "sync"
    "time"
)

type WorkerManager struct {
    sync.WaitGroup
}

func (wm *WorkerManager) AddWorker(worker func()) {
    wm.Add(1)
    go func() {
        defer wm.Done()
        worker()
    }()
}

const NumOfWorkers = 10

func main() {
    wm := &WorkerManager{}

    for i := 0; i <= NumOfWorkers; i++ {
        // you need to assign to variable to have access in the closure
        n := i
        wm.AddWorker(func() {
            time.Sleep(time.Duration(n) * time.Second)
            fmt.Printf("Worker #: %d\n", n)
        })
    }

    wm.Wait();
}
```

**Comment by storyfeet** [comment]
OK, which function is the problem in on my code?

Can I have some line numbers to look at please. I still don't see a race problem.

If it's where I think it is, then even if none of the workers start before the closing gofunc, we have no problem.  The channel that is listening on procDone will just wait until there is something in the channel. 



I get that we can use stdlib.  This was a learning execise for understanding channels.

**Comment by allyraza** [comment]
that was one thing I noticed there are other problems with you code you should accept it as constructive criticism and improve your knowledge by learning from others. I am by no means an expert on the language here is another problem.

```go
// you already know you have n number of workers hence the loop does n iterations
for i := 0; i < n; i++ {
		go func() {
                       // your loop here pull all the workers form the channel and run them in one single 
                      // routine perhaps you should just pull out the first worker and exec that
			for f := range res.main {
				f()
			}
			procDone <- true
		}()
	}
```

```go
for i := 0; i < n; i++ {
		go func() {
			f := <-res.main
          		f()
			procDone <- true
		}()
	}
```

**Comment by storyfeet** [comment]
One issue at a time please. feel free to raise other issues with my code, I do want to improve. 

However, when you do please do respectfully and kindly. Remember the first thing you did was to attack my understanding.

Take a look at how Davesh showed an improvement to my code, (same video, same codebase). and how I responded.  you could learn a thing or two from him about respectful dialog.

-- Edit : Devarsh not Davesh.

On this (new) issue, you are missunderstanding the code. it's not pulling workers from the channel, but jobs to do. 

in the test example there are 50 workers, but 1000 jobs to do.  the jobs are added by the Add() method belonging to the work group.

if you wish to discuss this more, create a new issue, so we don't get confused. Or just try fixing the code as you think it should be and running the test.

Back to the original issue, the race condition
---------

please tell me clearly what causes a race condition I have been searching for it all morning and I can't see it. I have even written another test, tht calls the first test 10,000 times. to see if I could get one race fail. it hasn't happened.
